[2024-08-19 07:36:18,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 07:36:18,093: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 07:36:18,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 07:36:18,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 07:36:18,101: INFO: common: created directory at: artifacts]
[2024-08-19 09:13:47,430: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:13:47,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:13:47,442: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:13:47,443: INFO: common: created directory at: artifacts]
[2024-08-19 09:13:47,443: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:13:47,548: ERROR: main: local variable 'result' referenced before assignment]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 105, in extract_workbench
    return result
UnboundLocalError: local variable 'result' referenced before assignment
[2024-08-19 09:40:44,869: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:40:44,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:40:44,872: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:40:44,873: INFO: common: created directory at: artifacts]
[2024-08-19 09:40:44,873: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:40:44,939: ERROR: main: local variable 'insert_query' referenced before assignment]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 89, in extract_workbench
    cursor.executemany(insert_query, values)
UnboundLocalError: local variable 'insert_query' referenced before assignment
[2024-08-19 09:41:12,922: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:41:12,924: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:41:12,925: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:41:12,926: INFO: common: created directory at: artifacts]
[2024-08-19 09:41:12,926: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:41:12,952: INFO: data_extraction: Extracteded data from database]
[2024-08-19 09:41:12,952: INFO: main: >>>>>> stage Data Extraction stage completed <<<<<<

x==========x]
[2024-08-19 09:41:12,971: INFO: main: *******************]
[2024-08-19 09:41:12,971: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-08-19 09:41:12,972: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:41:12,974: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:41:12,974: INFO: common: created directory at: artifacts]
[2024-08-19 09:41:12,975: INFO: data_train: Starting training]
[2024-08-19 09:41:12,981: INFO: common: Fitting Logistic Regression]
[2024-08-19 09:41:13,567: INFO: common: Best Parameters: {'algo__C': 0.5, 'algo__solver': 'newton-cg'}]
[2024-08-19 09:41:13,568: INFO: common: Best Score: 0.958]
[2024-08-19 09:41:13,571: INFO: common: Train and Test Accuracy Score for train 96.667 and test 100.0]
[2024-08-19 09:41:13,571: INFO: common: Finishing training]
[2024-08-19 09:41:13,581: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-08-19 09:41:39,378: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:41:39,379: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:41:39,380: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:41:39,381: INFO: common: created directory at: artifacts]
[2024-08-19 09:41:39,381: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:41:39,420: ERROR: main: local variable 'result' referenced before assignment]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 105, in extract_workbench
    return result
UnboundLocalError: local variable 'result' referenced before assignment
[2024-08-19 09:43:35,401: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:43:35,402: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:43:35,404: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:43:35,404: INFO: common: created directory at: artifacts]
[2024-08-19 09:43:35,404: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:43:35,426: ERROR: main: 1146 (42S02): Table 'iris_db.iris_data' doesn't exist]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Table 'iris_db.iris_data' doesn't exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 89, in extract_workbench
    cursor.executemany(insert_query, values)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 484, in executemany
    return self.execute(stmt)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'iris_db.iris_data' doesn't exist
[2024-08-19 09:44:01,076: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:44:01,077: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:44:01,078: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:44:01,079: INFO: common: created directory at: artifacts]
[2024-08-19 09:44:01,079: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:44:01,101: ERROR: main: 1265 (01000): Data truncated for column 'species' at row 1]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Data truncated for column 'species' at row 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 89, in extract_workbench
    cursor.executemany(insert_query, values)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 484, in executemany
    return self.execute(stmt)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'species' at row 1
[2024-08-19 09:45:59,393: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:45:59,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:45:59,397: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:45:59,397: INFO: common: created directory at: artifacts]
[2024-08-19 09:45:59,397: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:45:59,431: ERROR: main: 1265 (01000): Data truncated for column 'species' at row 1]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Data truncated for column 'species' at row 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 90, in extract_workbench
    cursor.executemany(insert_query, values)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 484, in executemany
    return self.execute(stmt)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 357, in execute
    result = self._connection.cmd_query(
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\opentelemetry\context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 1265 (01000): Data truncated for column 'species' at row 1
[2024-08-19 09:47:12,810: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:47:12,812: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:47:12,813: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:47:12,813: INFO: common: created directory at: artifacts]
[2024-08-19 09:47:12,813: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:47:12,842: ERROR: main: Failed executing the operation; Python type numpy.int64 cannot be converted]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 90, in extract_workbench
    cursor.executemany(insert_query, values)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 481, in executemany
    stmt = self._batch_insert(operation, seq_params)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\mysql\connector\cursor_cext.py", line 435, in _batch_insert
    raise InterfaceError(f"Failed executing the operation; {err}") from None
mysql.connector.errors.InterfaceError: Failed executing the operation; Python type numpy.int64 cannot be converted
[2024-08-19 09:48:58,208: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:48:58,209: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:48:58,210: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:48:58,210: INFO: common: created directory at: artifacts]
[2024-08-19 09:48:58,211: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:48:58,256: INFO: data_extraction: Extracteded data from database]
[2024-08-19 09:48:58,256: INFO: main: >>>>>> stage Data Extraction stage completed <<<<<<

x==========x]
[2024-08-19 09:48:58,267: INFO: main: *******************]
[2024-08-19 09:48:58,267: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-08-19 09:48:58,268: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:48:58,270: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:48:58,270: INFO: common: created directory at: artifacts]
[2024-08-19 09:48:58,271: INFO: data_train: Starting training]
[2024-08-19 09:48:58,273: INFO: common: Fitting Logistic Regression]
[2024-08-19 09:48:58,955: INFO: common: Best Parameters: {'algo__C': 0.5, 'algo__solver': 'newton-cg'}]
[2024-08-19 09:48:58,956: INFO: common: Best Score: 0.958]
[2024-08-19 09:48:58,958: INFO: common: Train and Test Accuracy Score for train 96.667 and test 100.0]
[2024-08-19 09:48:58,959: INFO: common: Finishing training]
[2024-08-19 09:48:58,966: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-08-19 09:49:26,636: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 09:49:26,637: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:49:26,639: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:49:26,639: INFO: common: created directory at: artifacts]
[2024-08-19 09:49:26,639: INFO: data_extraction: Extracting data from database]
[2024-08-19 09:49:26,673: INFO: data_extraction: Extracteded data from database]
[2024-08-19 09:49:26,674: INFO: main: >>>>>> stage Data Extraction stage completed <<<<<<

x==========x]
[2024-08-19 09:49:26,686: INFO: main: *******************]
[2024-08-19 09:49:26,686: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-08-19 09:49:26,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 09:49:26,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 09:49:26,689: INFO: common: created directory at: artifacts]
[2024-08-19 09:49:26,689: INFO: data_train: Starting training]
[2024-08-19 09:49:26,692: INFO: common: Fitting Logistic Regression]
[2024-08-19 09:49:27,339: INFO: common: Best Parameters: {'algo__C': 0.5, 'algo__solver': 'newton-cg'}]
[2024-08-19 09:49:27,340: INFO: common: Best Score: 0.958]
[2024-08-19 09:49:27,342: INFO: common: Train and Test Accuracy Score for train 96.667 and test 100.0]
[2024-08-19 09:49:27,343: INFO: common: Finishing training]
[2024-08-19 09:49:27,351: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-08-19 18:07:07,026: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-19 18:07:07,035: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:07:07,037: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:07:07,037: INFO: common: created directory at: artifacts]
[2024-08-19 18:07:07,039: INFO: data_extraction: Extracting data from database]
[2024-08-19 18:07:07,186: INFO: data_extraction: Extracteded data from database]
[2024-08-19 18:07:07,187: INFO: main: >>>>>> stage Data Extraction stage completed <<<<<<

x==========x]
[2024-08-19 18:07:07,201: INFO: main: *******************]
[2024-08-19 18:07:07,203: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-08-19 18:07:07,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:07:07,205: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:07:07,206: INFO: common: created directory at: artifacts]
[2024-08-19 18:07:07,206: INFO: data_train: Starting training]
[2024-08-19 18:07:07,209: INFO: common: Fitting Logistic Regression]
[2024-08-19 18:07:07,705: INFO: common: Best Parameters: {'algo__C': 0.5, 'algo__solver': 'newton-cg'}]
[2024-08-19 18:07:07,706: INFO: common: Best Score: 0.958]
[2024-08-19 18:07:07,708: INFO: common: Train and Test Accuracy Score for train 96.667 and test 100.0]
[2024-08-19 18:07:07,708: INFO: common: Finishing training]
[2024-08-19 18:07:07,718: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-08-19 18:07:21,937: INFO: app: *******************]
[2024-08-19 18:07:21,937: INFO: app: >>>>>> stage Predict started <<<<<<]
[2024-08-19 18:07:21,940: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:07:21,941: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:07:21,942: INFO: common: created directory at: artifacts]
[2024-08-19 18:07:21,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:07:21,945: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:07:21,946: INFO: common: created directory at: artifacts]
[2024-08-19 18:07:22,004: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-08-19 18:07:22,006: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-19 18:07:22,008: INFO: _internal:  * Restarting with stat]
[2024-08-19 18:07:23,833: INFO: app: *******************]
[2024-08-19 18:07:23,834: INFO: app: >>>>>> stage Predict started <<<<<<]
[2024-08-19 18:07:23,835: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:07:23,837: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:07:23,837: INFO: common: created directory at: artifacts]
[2024-08-19 18:07:23,839: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:07:23,840: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:07:23,841: INFO: common: created directory at: artifacts]
[2024-08-19 18:07:23,873: WARNING: _internal:  * Debugger is active!]
[2024-08-19 18:07:23,881: INFO: _internal:  * Debugger PIN: 775-250-452]
[2024-08-19 18:07:39,438: INFO: _internal: 127.0.0.1 - - [19/Aug/2024 18:07:39] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-19 18:08:37,126: INFO: _internal:  * Detected change in 'C:\\Users\\luisd\\OneDrive\\Escritorio\\proyecto trabajo\\Prueba1.0\\ABIChallenge_Luis-Romero\\src\\Classifier\\components\\data_predict.py', reloading]
[2024-08-19 18:08:37,314: INFO: _internal:  * Restarting with stat]
[2024-08-19 18:08:39,481: INFO: app: *******************]
[2024-08-19 18:08:39,481: INFO: app: >>>>>> stage Predict started <<<<<<]
[2024-08-19 18:08:39,483: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:08:39,485: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:08:39,485: INFO: common: created directory at: artifacts]
[2024-08-19 18:08:39,486: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-19 18:08:39,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-19 18:08:39,488: INFO: common: created directory at: artifacts]
[2024-08-19 18:08:39,524: WARNING: _internal:  * Debugger is active!]
[2024-08-19 18:08:39,534: INFO: _internal:  * Debugger PIN: 775-250-452]
[2024-08-19 18:08:49,699: INFO: _internal: 127.0.0.1 - - [19/Aug/2024 18:08:49] "POST /predict HTTP/1.1" 200 -]
[2024-08-19 18:10:03,202: INFO: app: >>>>>> stage Predict completed <<<<<<

x==========x]
[2024-08-19 18:10:03,343: INFO: app: >>>>>> stage Predict completed <<<<<<

x==========x]
[2024-08-20 05:24:50,172: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-20 05:24:50,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:24:50,187: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:24:50,188: INFO: common: created directory at: artifacts]
[2024-08-20 05:24:50,188: INFO: data_extraction: Extracting data from database]
[2024-08-20 05:24:50,268: INFO: data_extraction: Extracteded data from database]
[2024-08-20 05:24:50,268: INFO: main: >>>>>> stage Data Extraction stage completed <<<<<<

x==========x]
[2024-08-20 05:24:50,281: INFO: main: *******************]
[2024-08-20 05:24:50,282: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-08-20 05:24:50,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:24:50,283: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:24:50,284: INFO: common: created directory at: artifacts]
[2024-08-20 05:24:50,284: INFO: data_train: Starting training]
[2024-08-20 05:24:50,289: INFO: common: Fitting Logistic Regression]
[2024-08-20 05:24:50,716: INFO: common: Best Parameters: {'algo__C': 0.5, 'algo__solver': 'newton-cg'}]
[2024-08-20 05:24:50,716: INFO: common: Best Score: 0.958]
[2024-08-20 05:24:50,718: INFO: common: Train and Test Accuracy Score for train 96.667 and test 100.0]
[2024-08-20 05:24:50,718: INFO: common: Finishing training]
[2024-08-20 05:24:50,757: INFO: credentials: Found credentials in shared credentials file: ~/.aws/credentials]
[2024-08-20 05:24:51,001: ERROR: main: expected string or bytes-like object]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 27, in <module>
    model_training.main(df)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_02_data_train.py", line 17, in main
    training.run_train()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_train.py", line 75, in run_train
    s3.upload_fileobj(model_buffer, access_point, path_s3,ExtraArgs={'ACL': 'bucket-owner-full-control'})
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\boto3\s3\inject.py", line 635, in upload_fileobj
    future = manager.upload(
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\s3transfer\manager.py", line 323, in upload
    self._validate_if_bucket_supported(bucket)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\.venv\lib\site-packages\s3transfer\manager.py", line 492, in _validate_if_bucket_supported
    match = pattern.match(bucket)
TypeError: expected string or bytes-like object
[2024-08-20 05:26:36,710: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-20 05:26:36,711: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:26:36,713: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:26:36,713: INFO: common: created directory at: artifacts]
[2024-08-20 05:26:36,713: INFO: data_extraction: Extracting data from database]
[2024-08-20 05:26:57,799: ERROR: main: local variable 'connection' referenced before assignment]
Traceback (most recent call last):
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\main.py", line 13, in <module>
    df=obj.main()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\pipeline\Stage_01_data_extraction.py", line 17, in main
    return data_extraction.extract_info()
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\components\data_extraction.py", line 14, in extract_info
    self.data=extract_workbench(self.config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 64, in extract_workbench
    connection,cursor=conec_database(config)
  File "C:\Users\luisd\OneDrive\Escritorio\proyecto trabajo\Prueba1.0\ABIChallenge_Luis-Romero\src\Classifier\utils\common.py", line 53, in conec_database
    return connection,cursor
UnboundLocalError: local variable 'connection' referenced before assignment
[2024-08-20 05:29:17,733: INFO: main: >>>>>> stage Data Extraction stage started <<<<<<]
[2024-08-20 05:29:17,734: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:29:17,736: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:29:17,736: INFO: common: created directory at: artifacts]
[2024-08-20 05:29:17,736: INFO: data_extraction: Extracting data from database]
[2024-08-20 05:29:17,767: INFO: data_extraction: Extracteded data from database]
[2024-08-20 05:29:17,768: INFO: main: >>>>>> stage Data Extraction stage completed <<<<<<

x==========x]
[2024-08-20 05:29:17,777: INFO: main: *******************]
[2024-08-20 05:29:17,777: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-08-20 05:29:17,778: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:29:17,779: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:29:17,779: INFO: common: created directory at: artifacts]
[2024-08-20 05:29:17,780: INFO: data_train: Starting training]
[2024-08-20 05:29:17,782: INFO: common: Fitting Logistic Regression]
[2024-08-20 05:29:18,239: INFO: common: Best Parameters: {'algo__C': 0.5, 'algo__solver': 'newton-cg'}]
[2024-08-20 05:29:18,239: INFO: common: Best Score: 0.958]
[2024-08-20 05:29:18,241: INFO: common: Train and Test Accuracy Score for train 96.667 and test 100.0]
[2024-08-20 05:29:18,241: INFO: common: Finishing training]
[2024-08-20 05:29:18,249: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-08-20 05:29:28,634: INFO: app: *******************]
[2024-08-20 05:29:28,634: INFO: app: >>>>>> stage Predict started <<<<<<]
[2024-08-20 05:29:28,635: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:29:28,636: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:29:28,636: INFO: common: created directory at: artifacts]
[2024-08-20 05:29:28,637: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:29:28,638: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:29:28,639: INFO: common: created directory at: artifacts]
[2024-08-20 05:29:28,699: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000]
[2024-08-20 05:29:28,699: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-20 05:29:28,701: INFO: _internal:  * Restarting with stat]
[2024-08-20 05:29:30,024: INFO: app: *******************]
[2024-08-20 05:29:30,024: INFO: app: >>>>>> stage Predict started <<<<<<]
[2024-08-20 05:29:30,026: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:29:30,027: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:29:30,027: INFO: common: created directory at: artifacts]
[2024-08-20 05:29:30,028: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-20 05:29:30,029: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-20 05:29:30,030: INFO: common: created directory at: artifacts]
[2024-08-20 05:29:30,056: WARNING: _internal:  * Debugger is active!]
[2024-08-20 05:29:30,063: INFO: _internal:  * Debugger PIN: 775-250-452]
[2024-08-20 05:29:34,339: INFO: app: >>>>>> stage Predict completed <<<<<<

x==========x]
[2024-08-20 05:29:34,481: INFO: app: >>>>>> stage Predict completed <<<<<<

x==========x]
